repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        exclude: |
          (?x)(
              ^alembic/
          )
        args:
          - '--check'
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.3'
    hooks:
      - id: flake8
        exclude: |
          (?x)(
              ^alembic/
          )
