[tool.poetry]
name = "ricedb"
version = "0.1.0"
description = ""
authors = ["Lee Watson <rev@revthefox.co.uk>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.6"
irc3 = "^1.1"
markovify = "^0.7"
pylast = { version = "^3.1", optional = true }
ujson = "1.*"
requests = "^2.22"
sentry-sdk = { version = "^0.11", optional = true }
urllib3 = "^1.25"
beautifulsoup4 = "^4.8"

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
sentry = ["sentry-sdk"]
lastfm = ["pylast"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
