[tool.poetry]
name = "cappuccino"
version = "0.1.0"
description = ""
authors = ["Lee Watson <rev@revthefox.co.uk>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = ">=3.8, <4"
irc3 = "^1.1.0"
markovify = { version = "^0.8.0", optional = true}
pylast = { version = "^4.0.0", optional = true }
ujson = "^4.0.0"
requests = "^2.25.0"
sentry-sdk = { version = "^0.19.3", optional = true }
urllib3 = "^1.26.2"
beautifulsoup4 = "^4.9.0"
bottle = { version = "^0.12.19", optional = true }
sqlalchemy = { version = "^1.3.12", extras = ["postgresql"]}
alembic = "^1.4.0"
humanize = "^3.1.0"
html5lib = "^1.1"
ircstyle = "^0.1.1"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
sentry = ["sentry-sdk"]
lastfm = ["pylast"]
ai = ["markovify"]
web = ["bottle"]
all = ["bottle", "markovify", "pylast", "sentry-sdk"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
