[tool.poetry]
name = "cappuccino"
version = "0.1.0"
description = ""
authors = ["Lee Watson <rev@revthefox.co.uk>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = ">=3.8, <4"
irc3 = "^1.1.0"
markovify = "^0.8.0"
pylast = "^4.0.0"
ujson = "^4.0.0"
requests = "^2.25.0"
sentry-sdk = "^0.19.3"
urllib3 = "^1.26.2"
beautifulsoup4 = "^4.9.0"
bottle = "^0.12.19"
sqlalchemy = { version = "^1.3.12", extras = ["postgresql"] }
alembic = "^1.4.0"
humanize = "^3.1.0"
html5lib = "^1.1"
ircstyle = "^0.1.1"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.9.3"
flake8 = "^3.8.3"
black = "^20.8b1"

[tool.poetry.extras]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
