[tool.poetry]
name = "cappuccino"
version = "0.1.0"
description = ""
authors = ["Lee Watson <rev@revthefox.co.uk>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.8"
irc3 = "^1.1.0"
markovify = { version = "^0.8.0", optional = true}
pylast = { version = "^3.2.0", optional = true }
ujson = "^3.0.0"
requests = "^2.23.0"
sentry-sdk = { version = "^0.15.0", optional = true }
urllib3 = "^1.25.0"
beautifulsoup4 = "^4.8.0"
bottle = { version = "^0.12.0", optional = true }
sqlalchemy = { version = "^1.3.12", extras = ["postgresql"]}
ircmessage = { git = "https://github.com/FujiMakoto/IRC-Message", branch = "master" }
alembic = "^1.4.0"
humanize = "^2.0.0"

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
sentry = ["sentry-sdk"]
lastfm = ["pylast"]
ai = ["markovify"]
web = ["bottle"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
