[tool.poetry]
name = "ricedb"
version = "0.1.0"
description = ""
authors = ["Lee Watson <rev@revthefox.co.uk>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.6"
irc3 = "^1.1.0"
markovify = { version = "^0.7.0", optional = true}
pylast = { version = "^3.1.0", optional = true }
ujson = "^1"
requests = "^2.22.0"
sentry-sdk = { version = "^0.11.0", optional = true }
urllib3 = "^1.25.0"
beautifulsoup4 = "^4.8.0"
bottle = "^0.12.0"

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
sentry = ["sentry-sdk"]
lastfm = ["pylast"]
ai = ["markovify"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
